version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installation des dépendances..."
      - npm install
  pre_build:
    commands:
      - echo "Création du fichier .env avec VITE_API_BASE_URL"
      - echo "VITE_API_BASE_URL=${API_URL}" > .env
      - cat .env
  build:
    commands:
      - echo "Construction de l'application..."
      - npm run build
  post_build:
    commands:
      - echo "Déploiement sur S3..."
      - aws s3 rm s3://www.ai-pulse-news.com --recursive
      - aws s3 cp ./dist s3://www.ai-pulse-news.com --recursive
