export const categories = [
  "Apprentissage Automatique",
  "Apprentissage Profond",
  "Traitement du Langage Naturel",
  "Vision par Ordinateur",
  "IA & Robotique",
  "Réseaux de Neurones",
  "IA Quantique",
  "Éthique de l'IA",
  "Apprentissage par Renforcement",
  "IA & Santé",
  "IA & Finance",
  "IA Embarquée",
  "IA Explicable",
  "IA Générative",
  "Sécurité de l'IA",
  "Systèmes Autonomes",
  "Informatique Cognitive",
  "Matériel pour l'IA",
  "Recherche en IA",
  "Applications de l'IA",
  "Mises à Jour Majeures",
  "Nouvelles Fonctionnalités",
  "Améliorations de Performance",
  "Correctifs & Bugfixes",
  "Innovations Technologiques",
  "Intégrations & API",
  "Expériences Utilisateur",
  "Outils & Frameworks",
  "Compatibilité & Migration",
  "Roadmap & Perspectives"
];